package main

var auxiliaryNames = []string{
	"vision",
	"web_extract",
	"compression",
	"skills_hub",
	"approval",
	"mcp",
	"title_generation",
	"tts_audio_tags",
	"triage_specifier",
	"kanban_decomposer",
	"profile_describer",
	"curator",
	"monitor",
}

var modelProviderPresets = []ModelProviderPreset{
	{
		Key:          "dashscope-payg",
		Label:        "百炼按量计费",
		Provider:     "custom",
		BaseURL:      "https://dashscope.aliyuncs.com/compatible-mode/v1",
		APIMode:      "chat_completions",
		DefaultModel: "qwen3.7-max",
		ModelListURL: "https://dashscope.aliyuncs.com/compatible-mode/v1/models",
	},
	{
		Key:          "bailian-coding-plan",
		Label:        "百炼 Coding Plan",
		Provider:     "custom",
		BaseURL:      "https://coding.dashscope.aliyuncs.com/v1",
		APIMode:      "chat_completions",
		DefaultModel: "qwen3.7-max",
		ModelListURL: "https://coding.dashscope.aliyuncs.com/v1/models",
	},
	{
		Key:      "bailian-token-plan-team",
		Label:    "百炼 Token Plan 团队版",
		Provider: "custom",
		BaseURL:  "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
		APIMode:  "chat_completions",
	},
	{
		Key:          "zhipu-payg",
		Label:        "智谱按量计费",
		Provider:     "custom",
		BaseURL:      "https://open.bigmodel.cn/api/paas/v4",
		APIMode:      "chat_completions",
		DefaultModel: "glm-5.2",
		ModelListURL: "https://open.bigmodel.cn/api/paas/v4/models",
	},
	{
		Key:          "zhipu-coding-plan",
		Label:        "智谱 Coding Plan",
		Provider:     "custom",
		BaseURL:      "https://open.bigmodel.cn/api/coding/paas/v4",
		APIMode:      "chat_completions",
		DefaultModel: "glm-5.2",
		ModelListURL: "https://open.bigmodel.cn/api/coding/paas/v4/models",
	},
	{
		Key:          "volcengine-ark-coding-plan",
		Label:        "火山方舟 Coding Plan",
		Provider:     "custom",
		BaseURL:      "https://ark.cn-beijing.volces.com/api/coding/v3",
		APIMode:      "chat_completions",
		DefaultModel: "doubao-seed-2.0-code",
		ModelListURL: "https://ark.cn-beijing.volces.com/api/coding/v3/models",
	},
	{
		Key:          "opencode-go",
		Label:        "OpenCode Go",
		Provider:     "custom",
		BaseURL:      "https://opencode.ai/zen/go/v1",
		APIMode:      "chat_completions",
		DefaultModel: "deepseek-v4-flash",
		ModelListURL: "https://opencode.ai/zen/go/v1/models",
	},
	{
		Key:          "deepseek",
		Label:        "DeepSeek",
		Provider:     "deepseek",
		BaseURL:      "https://api.deepseek.com",
		APIMode:      "chat_completions",
		DefaultModel: "deepseek-v4-flash",
		ModelListURL: "https://api.deepseek.com/models",
	},
	{
		Key:          "agnes",
		Label:        "Agnes AI",
		Provider:     "custom",
		BaseURL:      "https://apihub.agnes-ai.com/v1",
		APIMode:      "chat_completions",
		DefaultModel: "agnes-2.0-flash",
		ModelListURL: "https://apihub.agnes-ai.com/v1/models",
	},
}
