export type Page = 'assistants' | 'operations';
export type WizardStep = 'model' | 'soul' | 'platforms' | 'finish';
export type OperationsTab = 'status' | 'deploy' | 'channels' | 'advanced';
export type PlatformKey = 'weixin' | 'wecom' | 'feishu';

export type EnvVar = { key: string; value: string; secret: boolean };
export type ComposeSettings = {
    image: string;
    containerName: string;
    gatewayHost: string;
    gatewayPort: string;
    dashboardHost: string;
    dashboardPort: string;
    dashboardEnabled: boolean;
    dashboardUsername: string;
    dashboardPassword: string;
    gatewayBusyInputMode: string;
    gatewayBusyAckEnabled: string;
    backgroundNotifications: string;
    memoryLimit: string;
    cpuLimit: string;
    shmSize: string;
};
export type AuxModel = { provider: string; model: string; baseUrl: string; apiKey: string; timeout: number; extraBody: Record<string, unknown> };
export type ModelConfig = {
    provider: string;
    default: string;
    baseUrl: string;
    apiMode: string;
    apiKey: string;
    auxiliaryMode: string;
    auxiliary: Record<string, AuxModel>;
};
export type ModelProviderPreset = {
    key: string;
    label: string;
    provider: string;
    baseUrl: string;
    apiMode: string;
    defaultModel: string;
    modelListUrl: string;
};
export type ProviderEntry = {
    label: string;
    provider: string;
    baseUrl: string;
    apiMode: string;
    apiKey: string;
    modelListUrl: string;
    defaultModel: string;
    builtin: boolean;
    disabled: boolean;
};
export type ProviderConfig = { providers: Record<string, ProviderEntry> };
export type ModelListRequest = { providerId: string; providerKey: string; apiKey: string; baseUrl: string };
export type ModelOption = { id: string; ownedBy: string };
export type ChannelSummary = { id: string; name: string; type: string; thread_id?: string };
export type ChannelFile = { updated_at: string; platforms: Record<string, ChannelSummary[]> };
export type ProfileEntry = { id: string; name: string; enabled: boolean; createdAt: string; updatedAt: string; modelAuxiliaryMode: string; setupCompletedAt?: string };
export type ProfileRegistry = { schemaVersion: number; profiles: ProfileEntry[] };
export type RuntimeProfileStatus = { enabled: boolean; state: string; pid: number; startedAt: string; lastExitCode: number; restartCount: number; message: string };
export type RuntimeStatus = { updatedAt: string; profiles: Record<string, RuntimeProfileStatus> };
export type SkillSummary = {
    name: string;
    description: string;
    version: string;
    author: string;
    platforms: string[];
    tags: string[];
    path: string;
    category: string;
    builtin: boolean;
    conflict: boolean;
    error: string;
    sizeBytes: number;
    updatedAt: string;
};
export type SkillsState = {
    activeProfile: string;
    skills: SkillSummary[];
    total: number;
    builtinCount: number;
    customCount: number;
    conflictCount: number;
};
export type SkillFileInfo = { path: string; sizeBytes: number; updatedAt: string };
export type SkillDetail = SkillSummary & {
    preview: string;
    previewTruncated: boolean;
    files: SkillFileInfo[];
    fileCount: number;
    filesTruncated: boolean;
    conflictPaths: string[];
};
export type Notice = { type: 'ok' | 'error' | 'info'; message: string };
export type RunOptions = { rebuildRequired?: boolean; beforeRefresh?: () => void; afterSuccess?: () => void };
export type AppState = {
    appVersion: string;
    instanceRoot: string;
    profiles: ProfileRegistry;
    activeProfile: string;
    profileStatus: RuntimeStatus;
    compose: ComposeSettings;
    environment: EnvVar[];
    model: ModelConfig;
    providers: ProviderConfig;
    channels: ChannelFile;
    dockerAvailable: boolean;
    composeAvailable: boolean;
    containerStatus: string;
};
