// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelWeixinLogin():Promise<void>;

export function ChangeWebPassword(arg1:string,arg2:string):Promise<void>;

export function CheckForUpdates(arg1:boolean):Promise<main.UpdateInfo>;

export function CompleteProfileSetup(arg1:string):Promise<void>;

export function CreateProfile(arg1:main.CreateProfileRequest):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DismissUpdate(arg1:string):Promise<void>;

export function FactoryResetInstance():Promise<void>;

export function FetchModelList(arg1:main.ModelListRequest):Promise<Array<main.ModelOption>>;

export function FetchProviderConfigModelList(arg1:main.ProviderConfigEntry):Promise<Array<main.ModelOption>>;

export function FetchProviderModelList(arg1:string):Promise<Array<main.ModelOption>>;

export function GetAppState():Promise<main.AppState>;

export function GetChannels():Promise<main.ChannelFile>;

export function GetModelProviderPresets():Promise<Array<main.ModelProviderPreset>>;

export function GetProviderConfig():Promise<main.ProviderConfig>;

export function GetSkillDetail(arg1:string):Promise<main.SkillDetail>;

export function GetSkillHubDetail(arg1:string):Promise<main.SkillHubDetail>;

export function InitializeInstance(arg1:main.ComposeSettings):Promise<main.LauncherState>;

export function InstallSkillHubSkill(arg1:string):Promise<void>;

export function ListProfileSkills():Promise<main.SkillsState>;

export function ListProfiles():Promise<main.ProfileRegistry>;

export function ListSkillHubSkills(arg1:main.SkillHubQuery):Promise<main.SkillHubState>;

export function MoveProfile(arg1:string,arg2:string):Promise<void>;

export function OpenEndpoint(arg1:string):Promise<void>;

export function OpenSkillDirectory(arg1:string):Promise<void>;

export function OpenUpdateURL(arg1:string):Promise<void>;

export function OpenWebManagement():Promise<void>;

export function ReadTextFile(arg1:string):Promise<string>;

export function RebuildHermes():Promise<void>;

export function ResetWebPassword():Promise<void>;

export function RestartHermes():Promise<void>;

export function RestoreDefaultSkills():Promise<main.SyncBundledSkillsResult>;

export function RestoreDefaultSoul():Promise<void>;

export function SaveComposeSettings(arg1:main.ComposeSettings):Promise<void>;

export function SaveEnvironment(arg1:Array<main.EnvVar>):Promise<void>;

export function SaveFeishuConfig(arg1:main.FeishuConfig):Promise<void>;

export function SaveModelConfig(arg1:main.ModelConfig):Promise<void>;

export function SaveProviderConfig(arg1:main.ProviderConfig):Promise<void>;

export function SaveProxySettings(arg1:main.ProxySettings):Promise<void>;

export function SaveTextFile(arg1:main.TextFileRequest):Promise<void>;

export function SaveWeComConfig(arg1:main.WeComConfig):Promise<void>;

export function SaveWebSettings(arg1:main.WebSettingsRequest):Promise<void>;

export function SelectProfile(arg1:string):Promise<void>;

export function SendTestMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetHomeChannel(arg1:string,arg2:string):Promise<void>;

export function SetProfileEnabled(arg1:string,arg2:boolean):Promise<void>;

export function StartHermes():Promise<void>;

export function StartWeixinLogin():Promise<void>;

export function StopHermes():Promise<void>;

export function StopTailLogs():Promise<void>;

export function SyncBundledSkills():Promise<main.SyncBundledSkillsResult>;

export function TailLogs():Promise<void>;

export function TestModel():Promise<void>;

export function UnbindPlatform(arg1:string):Promise<void>;

export function UpdateProfileName(arg1:string,arg2:string):Promise<void>;
