// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelWeixinLogin():Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function FactoryResetInstance():Promise<void>;

export function FetchModelList(arg1:main.ModelListRequest):Promise<Array<main.ModelOption>>;

export function FetchProviderConfigModelList(arg1:main.ProviderConfigEntry):Promise<Array<main.ModelOption>>;

export function FetchProviderModelList(arg1:string):Promise<Array<main.ModelOption>>;

export function GetAppState():Promise<main.AppState>;

export function GetChannels():Promise<main.ChannelFile>;

export function GetModelProviderPresets():Promise<Array<main.ModelProviderPreset>>;

export function GetProviderConfig():Promise<main.ProviderConfig>;

export function InitializeInstance(arg1:main.ComposeSettings):Promise<main.LauncherState>;

export function OpenEndpoint(arg1:string):Promise<void>;

export function ReadTextFile(arg1:string):Promise<string>;

export function RebuildHermes():Promise<void>;

export function RestartHermes():Promise<void>;

export function SaveComposeSettings(arg1:main.ComposeSettings):Promise<void>;

export function SaveEnvironment(arg1:Array<main.EnvVar>):Promise<void>;

export function SaveModelConfig(arg1:main.ModelConfig):Promise<void>;

export function SaveProviderConfig(arg1:main.ProviderConfig):Promise<void>;

export function SaveTextFile(arg1:main.TextFileRequest):Promise<void>;

export function SaveWeComConfig(arg1:main.WeComConfig):Promise<void>;

export function SendTestMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetHomeChannel(arg1:string,arg2:string):Promise<void>;

export function StartHermes():Promise<void>;

export function StartWeixinLogin():Promise<void>;

export function StopHermes():Promise<void>;

export function StopTailLogs():Promise<void>;

export function TailLogs():Promise<void>;

export function TestModel():Promise<void>;
