// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelWeixinLogin() {
  return window['go']['main']['App']['CancelWeixinLogin']();
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function FactoryResetInstance() {
  return window['go']['main']['App']['FactoryResetInstance']();
}

export function FetchModelList(arg1) {
  return window['go']['main']['App']['FetchModelList'](arg1);
}

export function FetchProviderConfigModelList(arg1) {
  return window['go']['main']['App']['FetchProviderConfigModelList'](arg1);
}

export function FetchProviderModelList(arg1) {
  return window['go']['main']['App']['FetchProviderModelList'](arg1);
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetChannels() {
  return window['go']['main']['App']['GetChannels']();
}

export function GetModelProviderPresets() {
  return window['go']['main']['App']['GetModelProviderPresets']();
}

export function GetProviderConfig() {
  return window['go']['main']['App']['GetProviderConfig']();
}

export function InitializeInstance(arg1) {
  return window['go']['main']['App']['InitializeInstance'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function MoveProfile(arg1, arg2) {
  return window['go']['main']['App']['MoveProfile'](arg1, arg2);
}

export function OpenEndpoint(arg1) {
  return window['go']['main']['App']['OpenEndpoint'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function RebuildHermes() {
  return window['go']['main']['App']['RebuildHermes']();
}

export function RestartHermes() {
  return window['go']['main']['App']['RestartHermes']();
}

export function SaveComposeSettings(arg1) {
  return window['go']['main']['App']['SaveComposeSettings'](arg1);
}

export function SaveEnvironment(arg1) {
  return window['go']['main']['App']['SaveEnvironment'](arg1);
}

export function SaveFeishuConfig(arg1) {
  return window['go']['main']['App']['SaveFeishuConfig'](arg1);
}

export function SaveModelConfig(arg1) {
  return window['go']['main']['App']['SaveModelConfig'](arg1);
}

export function SaveProviderConfig(arg1) {
  return window['go']['main']['App']['SaveProviderConfig'](arg1);
}

export function SaveTextFile(arg1) {
  return window['go']['main']['App']['SaveTextFile'](arg1);
}

export function SaveWeComConfig(arg1) {
  return window['go']['main']['App']['SaveWeComConfig'](arg1);
}

export function SelectProfile(arg1) {
  return window['go']['main']['App']['SelectProfile'](arg1);
}

export function SendTestMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendTestMessage'](arg1, arg2, arg3);
}

export function SetHomeChannel(arg1, arg2) {
  return window['go']['main']['App']['SetHomeChannel'](arg1, arg2);
}

export function SetProfileEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetProfileEnabled'](arg1, arg2);
}

export function StartHermes() {
  return window['go']['main']['App']['StartHermes']();
}

export function StartWeixinLogin() {
  return window['go']['main']['App']['StartWeixinLogin']();
}

export function StopHermes() {
  return window['go']['main']['App']['StopHermes']();
}

export function StopTailLogs() {
  return window['go']['main']['App']['StopTailLogs']();
}

export function TailLogs() {
  return window['go']['main']['App']['TailLogs']();
}

export function TestModel() {
  return window['go']['main']['App']['TestModel']();
}

export function UpdateProfileName(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfileName'](arg1, arg2);
}
